# **1.Numpy 란?**

* 수학, 과학 계산용 패키지
* 성능 : 파이썬 리스트보다 빠름
* 메모리 사이즈 : 파이썬 리스트보다 적은 메모리를 사용
* 빌트인 함수 : 선형대수, 통계관련 여러 함수들을 내장

In [1]:
import numpy

In [2]:
numpy

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [3]:
# 별칭(alias) 지정 
import numpy as np

In [4]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

### **1-1. array(배열)**
* 여러 값들의 그룹

In [11]:
arr = np.array([1,2,3,4])

In [12]:
arr

array([1, 2, 3, 4])

In [13]:
type(arr) #ndarray = n dimension array

numpy.ndarray

In [14]:
list1 = [1,2,3,4]
list2 = [[1,2,3,4],[5,6,7,8]]
print(list1)
print(list2)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [15]:
# 리스트로 부터 np.array 생성
arr1 = np.array(list1)
arr2 = np.array(list2)

In [16]:
arr1.shape # 차원 -> 1차원

(4,)

In [17]:
arr2.shape # 차원 -> 2차원 (2 X 4 matrix)

(2, 4)

### **1-2. array에서의 data타입**
* array에서는 list와는 다르게 1개의 단일 데이터 타입만 허용

In [18]:
list = [1, 3.14, '😍', '1234']
print(list)
print(list[2])

[1, 3.14, '😍', '1234']
😍


In [19]:
# int와 float 타입이 같은 존재하는 경우
arr = np.array([1,2,3,3.14]) # 제일 큰 타입으로 저장 
print(arr) # float 타입으로 저장

[1.   2.   3.   3.14]


In [20]:
# int와 float 타입이 같이 존재하는 경우, dtype을 int로 설정
arr = np.array([1,2,3,3.14], dtype = int)
arr

array([1, 2, 3, 3])

In [21]:
# int와 str 타입이 같이 존재하는 경우
arr = np.array([1,3.14,'😂', '1234'])
arr

array(['1', '3.14', '😂', '1234'], dtype='<U32')

In [22]:
arr[0] + arr[1]

'13.14'

In [25]:
# int와 str 타입이 같이 존재하는 경우, dtype을 int로 설정
# 숫자로 이루어진 문자열외에는 변경 불가능
arr = np.array([1,3.14, '🤣', '1234'], dtype = int)

ValueError: ignored

In [26]:
arr = np.array([1,3.14, '1234'], dtype = int)
arr

array([   1,    3, 1234])

### **1-3. 슬라이싱**
* 배열의 부분 선택

In [27]:
arr = np.array(['👌','💕', '❤️','12', '23'])
arr.shape

(5,)

In [28]:
# index 지정하여 색인
arr = np.array(['👌','💕', '❤️'])
print(arr)
print(arr[0])
print(arr[2])

['👌' '💕' '❤️']
👌
❤️


In [29]:
# 2차원 array
arr2d = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
print(arr2d.shape)
print(arr2d[0,2])
print(arr2d[2,1])


(3, 4)
3
10


In [30]:
# 범위 색인
arr

array(['👌', '💕', '❤️'], dtype='<U2')

In [31]:
# index 1 이상 끝까지
arr[1:]

array(['💕', '❤️'], dtype='<U2')

In [32]:
#index 3미만까지
arr[:3]

array(['👌', '💕', '❤️'], dtype='<U2')

In [33]:
#index 1이상 3미만
arr[1:3]

array(['💕', '❤️'], dtype='<U2')

In [34]:
arr[:-1]

array(['👌', '💕'], dtype='<U2')

In [35]:
arr2d = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [36]:
#row(행)을 모두 가져오기
arr2d[0, : ]

array([1, 2, 3, 4])

In [37]:
# 1 col(열) 모두 가져오기
arr2d[:, 1]

array([ 2,  6, 10])

In [38]:
arr2d[:2, :] # 뒷부분 모든 열을 가져온다 , 앞부분은 2가 되기 전

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

### **1-4. Fancy 인덱싱**
* 범위가 아닌 특정 index의 집합의 값을 선택하여 추출하고 싶을 때 활용

In [40]:
arr = np.array([10,23,2,7,90,65,32,66,70])

In [41]:
idx = [1,3,5]

In [42]:
arr[idx]

array([23,  7, 65])

In [43]:
arr2d = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [44]:
arr2d[[0,1], :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### **1-5. Boolean 인덱싱**
* 조건 필터링을 통하여 Boolean 값을 이용한 색인

In [45]:
arr = np.array(['👌','💕', '❤️','12', '23'])
arr2d = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])

In [46]:
#True와 False 값으로 색인
myValue = [True, False, True]

In [47]:
arr[myValue] # 에러 이유: dimension값이 다르다

IndexError: ignored

In [48]:
myValue = [True, False, True, True, False]

In [49]:
arr[myValue]

array(['👌', '❤️', '12'], dtype='<U2')

In [58]:
# 조건 필터
arr2d > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [59]:
arr2d[arr2d>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [60]:
arr2d[arr2d>5]

array([ 6,  7,  8,  9, 10, 11, 12])

# **2. Matrix(행렬)**

### **2-1. Matrix**
* 행(row) + 열(column)

> 데이터분석 및 기계학습에 있어서 행렬을 빼놓고 얘기할 수 없음

덧셈
* shape가 같아야 함
* 같은 position끼리 연산

뺄셈
* shape가 같아야 함
* 같은 position끼리 연산

곱셈
* 맞닿는 shape가 같아야 함

  ex) 2 * 3 X 3 * 1 = 2 * 1


### **2-2. arange 란?**
* arange : 순차적인 값을 생성할 때 사용

In [68]:
import numpy as np

In [69]:
arr = [1,2,3,4,5,6,7,8,9,10]

In [70]:
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [71]:
arr = np.arange(1, 11) # 1부터 11미만의 수

In [72]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr = np.arange(start = 1, stop = 11, step =5) 
#왜 start와 stop 쓰는지? -> 가독성,

In [79]:
arr

array([1, 6])

### **2-3. range(numpy와는 상관없는 python문법)**
range는 범위를 지정해주는 함수
보통 for in의 반복문에서 많이 사용

In [80]:
arr = np.arange(1, 11)
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10


In [81]:
for i in range(1, 11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [83]:
for i in range(1, 11, 2):
  print(i)

1
3
5
7
9


### **2-4. 정렬(sort)**

In [88]:
arr= np.array([1, 10, 5, 8 ,2,4, 3, 6, 8,7,9])

In [89]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [90]:
np.sort(arr) # 기본적으로 오름차순 정렬

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [92]:
np.sort(arr)[::-1] # 내림차순 정렬은 -1 값을 설정, 값이 유지되지 않음

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [93]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [94]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [95]:
result = np.sort(arr)
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [106]:
# N차원 정렬

arr2d = np.array([[12,2,9,4],
                 [7,10,1,8],
                 [9,6,11,3]])

In [104]:
arr2d.shape

(2, 4)

In [107]:
arr2d

array([[12,  2,  9,  4],
       [ 7, 10,  1,  8],
       [ 9,  6, 11,  3]])

In [111]:
#열 정렬(왼쪽에서 오른쪽으로)
# axis = 1, 행

np.sort(a= arr2d, axis = 1)

array([[ 2,  4,  9, 12],
       [ 1,  7,  8, 10],
       [ 3,  6,  9, 11]])

In [112]:
# 행 정렬(위에서 아래로)
# axis = 0, 열

np.sort(a = arr2d, axis = 0)

array([[ 7,  2,  1,  3],
       [ 9,  6,  9,  4],
       [12, 10, 11,  8]])

In [113]:
#index를 반환하는 argsort

arr2d = np.array([[12,2,9,4],
                 [7,10,1,8],
                 [9,6,11,3]])

In [114]:
np.argsort(arr2d, axis = 1)

array([[1, 3, 2, 0],
       [2, 0, 3, 1],
       [3, 1, 0, 2]])

In [115]:
np.argsort(arr2d, axis = 0)

array([[1, 0, 1, 2],
       [2, 2, 0, 0],
       [0, 1, 2, 1]])

In [116]:
arr2d = np.array([[1,5,6,8],
                 [10,4,8,1],
                 [3,4,8,6]])


### **2-5. 행렬 - 덧셈**

In [117]:
import numpy as np

In [118]:
# 덧셈
a = np.array([[1, 2, 3],
             [2, 3, 4]])

b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [119]:
a + b

array([[4, 6, 8],
       [3, 5, 7]])

In [120]:
a = np.array([[1, 2, 3],
             [2, 3, 4]])

b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [121]:
a + b # 다른 shape

ValueError: ignored

In [122]:
# sum
a = np.array([[1, 2, 3],
              [2, 3, 4]])

In [123]:
np.sum(a, axis=0) #열 씩 계산

array([3, 5, 7])

In [124]:
np.sum(a, axis=1) # 행 계산

array([6, 9])

### **2-6. 행렬의 뺄셈**

In [125]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [126]:
a - b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [127]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [128]:
a - b

ValueError: ignored

### **2-7. 행렬의 곱셈**

In [129]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [130]:
print(a.shape)
print(b.shape)

(2, 3)
(2, 3)


In [131]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

> 단순 곱셈과 dot product는 다름

In [132]:
a = np.array([[1, 2, 3],
              [1, 2, 3],
              [2, 3, 4]])

b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [133]:
a.shape, b.shape


((3, 3), (3, 2))

In [134]:
np.dot(a,b)

array([[22, 28],
       [22, 28],
       [31, 40]])

# **3. broadcasting**

### **1-1. 숫자의 연산(단일)**

In [135]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

b = np.array([[1, 2,3],
              [3,3,3]])

In [136]:
a+b

array([[2, 4, 6],
       [5, 6, 7]])

In [137]:
a+3

array([[4, 5, 6],
       [5, 6, 7]])

In [138]:
a-3

array([[-2, -1,  0],
       [-1,  0,  1]])

In [139]:
a*3

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [140]:
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])

In [141]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[1],
             [2]])

In [142]:
a.shape, b.shape

((2, 3), (2, 1))

In [143]:
a * b

array([[1, 2, 3],
       [4, 6, 8]])